version: 3

dotenv: ['.env']

tasks:
  run:
    cmds:
      - DISCORD_TOKEN=$DISCORD_TOKEN
        DISCORD_ICON_URL=$DISCORD_ICON_URL
        RCON_HOST=$RCON_HOST
        RCON_PORT=$RCON_PORT
        RCON_PASSWORD=$RCON_PASSWORD
        go run cmd/main.go
