version: 3

dotenv: ['.env']

tasks:
  run:
    cmds:
      - DISCORD_TOKEN=$DISCORD_TOKEN
        DISCORD_ICON_URL=$DISCORD_ICON_URL
        API_HOST=$API_HOST
        API_PORT=$API_PORT
        API_PASSWORD=$API_PASSWORD
        go run cmd/main.go
